#!/bin/sh

get_wifi_connection() {
  ssid=$(nmcli -t -f active,ssid dev wifi | grep '^yes' | cut -d: -f2)
  if [ -n "$ssid" ]; then
    echo "Connected"
  else
    echo "Disconnected"
  fi
}

get_wifi_connection
